server:
  port: 8080
  maxHttpHeaderSize: 10240
  URIEncoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherinfo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
<<<<<<< HEAD
    driver-class-name: com.mysql.jdbc.Driver
=======
    driver-class-name: com.mysql.jdbc.Driver
>>>>>>> b09f41f58444330811616593f30ec5d5c7034708
